### ISSUE TITLE
Javadoc location

### ISSUE THREAD

**Issue by cutlope** [madhavd1/vscode-javadoc-tools#5]
By default, it attempts to to run javadoc from the JAVA_HOME system variable,
Shouldn't it be running it from the jdk path listed in Vscode?

**Comment by madhavd1** [comment]
Heloo @euess,
Thanks for you patience. I was not able to check and update the plugin since last year and I've started looking into this.

The extension first checks "java.home" variable for the jdk path. If that is unavailable, it will fallback to JAVA_HOME env variable.
Is your jdk path listed in "java.home"?
